# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Build your .NET Core project (but avoid restore your packages again)

- task: DotNetCoreCLI@2
  displayName: ".NET build"
  inputs:
    projects: '**/*.csproj'
    arguments: ''

# Run your unit tests

- task: DotNetCoreCLI@2
  displayName: ".NET test"
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'

#iOS

- task: CocoaPods@0
  inputs:
    workingDirectory: './Client/iOS/MyToDoList/'
    forceRepoUpdate: false


- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'MyToDoList'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/MyToDoList.xcworkspace'
    xcodeVersion: '10' # Options: 8, 9, 10, default, specifyPath
    signingOption: 'nosign' # Options: nosign, default, manual, auto

- task: Xcode@5
  inputs:
    actions: 'test'
    scheme: 'MyToDoListTests'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/MyToDoList.xcworkspace'
    xcodeVersion: '10' # Options: 8, 9, 10, default, specifyPath
    signingOption: 'nosign' # Options: nosign, default, manual, auto

